Avoids tox/pip failures on old systems
Some systems may have older virtualenv versions which would install
an ancient version of pip (like 8.1.1) which is not able to parse
requirements correctly generating errors like:

RequirementParseError: Expected ',' or end-of-list in pathlib2>=2.2.0;python_version<"3.6" at ;python_version<"3.6"
You are using pip version 8.1.1, however version 19.1.1 is available.

We cannot really support such versions so we can assure that we
only run with relatively newer tools.

This should fixed observed AppVeyor errors.